package org.dam.tfg.enums

enum class Estilo {
    BAREBOW_RECURVED,
    BAREBOW_COMPOUND,
    FREESTYLE_UNLIMITED,
    FREESTYLE_LIMITED_RECURVED,
    FREESTYLE_LIMITED_COMPUND,
    BOWHUNTER_RECURVED,
    BOWHUNTER_COMPOUND,
    BOWHUNTER_UNLIMITED,
    BOWHUNTER_LIMITED,
    LONGBOW,
    HISTORICO,
    TRADICIONAL
}